{
  "_annotation": {
    "cve_id": "CVE-2024-28233",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-28233.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:jupyter:jupyterhub:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "AB3E1D2E-50AD-5732-ACFE-D91CCC2E646C",
                "versionEndExcluding": "4.1.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}