{
  "_annotation": {
    "cve_id": "CVE-2024-36112",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-36112.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:networktocode:nautobot:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "93AD9437-C7A6-5483-BB61-397B21465413",
                "versionEndExcluding": "1.6.23",
                "versionStartIncluding": "1.3.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:networktocode:nautobot:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "75177716-A3C1-50C3-AAFA-0296617CE5C1",
                "versionEndExcluding": "2.2.5",
                "versionStartIncluding": "2.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}