{
  "_annotation": {
    "cve_id": "CVE-2024-37891",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-37891.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:urllib3:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "66F70B60-BB0C-55FF-AEE8-6E199628706A",
                "versionEndExcluding": "1.26.19",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:urllib3:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "274BD4CD-0DE3-5401-8AA7-00977721F99B",
                "versionEndExcluding": "2.2.2",
                "versionStartIncluding": "2.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}