{
  "_annotation": {
    "cve_id": "CVE-2024-41942",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2024/CVE-2024-41942.json",
    "reason": "Added CPE configurations because not yet analyzed by NVD."
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:jupyter:jupyterhub:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "58742882-0D06-5F1C-9CB6-678BA5CB7CDD",
                "versionEndExcluding": "4.1.6",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:jupyter:jupyterhub:*:*:*:*:*:python:*:*",
                "matchCriteriaId": "D82D637A-3A76-5EB2-A087-00AB6CE20F19",
                "versionEndExcluding": "5.1.0",
                "versionStartIncluding": "5.0.0",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}