{
  "_annotation": {
    "cve_id": "CVE-2023-38898",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2023/CVE-2023-38898.json",
    "reason": "Improve version ranges to indicate fix"
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "1D1EC602-5469-57AB-84E0-5CE8E496958E",
                "versionEndExcluding": "3.13.0a1",
                "versionStartIncluding": "3.13.0a0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "AB422B91-8323-556C-B0D9-2C57EAD23D11",
                "versionEndExcluding": "3.12.0b4",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}