{
  "_annotation": {
    "cve_id": "CVE-2023-6507",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2023/CVE-2023-6507.json",
    "reason": "Improve version ranges to indicate fix"
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "37C64B45-6774-5E41-BE0E-DCAFA02DF6F7",
                "versionEndExcluding": "3.12.1",
                "versionStartIncluding": "3.12.0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "CBEE1279-724C-5FC5-B818-D08191D83A8E",
                "versionEndExcluding": "3.13.0a3",
                "versionStartIncluding": "3.13.0a1",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}