{
  "_annotation": {
    "cve_id": "CVE-2022-39408",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2022/CVE-2022-39408.json",
    "reason": "Improve version ranges to indicate fix"
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:oracle:mysql:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "DADBB2D8-646B-5BE8-8C71-F77A0A87368B",
                "versionEndExcluding": "8.0.31",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          },
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:oracle:mysql_server:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "B60473D9-F7E8-5AFE-B66C-0BF7C554683D",
                "versionEndExcluding": "8.0.31",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}