{
  "advisory_id": "pypi/Flask/CVE-2019-1010083",
  "aliases": ["CVE-2019-1010083"],
  "summary": "Denial of service\nDenial of Service due to unexpected memory usage in the Pallets Project Flask",
  "affected_packages": [
    {
      "package": {
        "type": "pypi",
        "namespace": "",
        "name": "flask",
        "version": "",
        "qualifiers": "",
        "subpath": ""
      },
      "affected_version_range": "vers:pypi/<1.0",
      "fixed_version_range": "vers:pypi/1.0"
    }
  ],
  "references_v2": [
    {
      "reference_id": "CVE-2019-1010083",
      "reference_type": "",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-1010083"
    },
    {
      "reference_id": "",
      "reference_type": "",
      "url": "https://www.palletsprojects.com/blog/flask-1-0-released/"
    }
  ],
  "severities": [],
  "date_published": "2019-07-17T00:00:00+00:00",
  "weaknesses": [1035, 937],
  "url": "https://gitlab.com/gitlab-org/advisories-community/-/blob/main/pypi/Flask/CVE-2019-1010083.yml"
}
