{
  "_annotation": {
    "cve_id": "CVE-2021-3177",
    "generated_from": "https://raw.githubusercontent.com/anchore/cve-data-enrichment/main/data/anchore/2021/CVE-2021-3177.json",
    "reason": "Improve version ranges to indicate fix"
  },
  "cve": {
    "configurations": [
      {
        "nodes": [
          {
            "cpeMatch": [
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "85737AEE-90EF-57B6-A8EC-0566F3AE02F5",
                "versionEndExcluding": "3.10.0",
                "versionStartIncluding": "3.10.0a0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "E6A8941F-6FAA-58DE-9AFC-8128334B9229",
                "versionEndExcluding": "3.9.2",
                "versionStartIncluding": "3.9.0a0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "A39EFA7C-3D61-55CB-8E5F-30C1C850CEF1",
                "versionEndExcluding": "3.8.8",
                "versionStartIncluding": "3.8.0a0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "A834D1EF-9679-5F1D-BAF7-BA407C89608F",
                "versionEndExcluding": "3.7.10",
                "versionStartIncluding": "3.7.0a0",
                "vulnerable": true
              },
              {
                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                "matchCriteriaId": "BB8842D9-B554-4B83-9E2E-0FAF292E448A",
                "versionEndExcluding": "3.6.13",
                "vulnerable": true
              }
            ],
            "negate": false,
            "operator": "OR"
          }
        ]
      }
    ]
  }
}